add dependencies to deploy script

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -58,6 +58,73 @@ jobs:
         with:
           ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
 
+      - name: Server setup lines
+        run: |
+          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST }} << 'EOF'
+            if [ ! -d "IDE-autograder" ]; then
+                git clone git@github.com:Classla/IDE-autograder.git
+            else
+                echo "IDE-autograder repository already exists, skipping clone."
+            fi
+
+            sudo apt-get update -y
+            sudo apt-get upgrade -y
+            sudo apt-get install python3 python3-pip -y
+            sudo apt-get install git -y
+
+            pip install virtualenv
+            virtualenv autograder_env
+            source autograder_env/bin/activate
+            pip install -r requirements.txt
+
+            if ! command -v docker &> /dev/null
+            then
+                echo "Docker not found, installing Docker..."
+
+                sudo apt-get install -y \
+                apt-transport-https \
+                ca-certificates \
+                curl \
+                software-properties-common
+                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
+                echo \
+                "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
+                $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+                sudo apt-get update
+                sudo apt-get install -y docker-ce docker-ce-cli containerd.io
+                sudo usermod -aG docker $USER
+                newgrp docker
+                echo "Docker installation complete."
+            else
+                echo "Docker is already installed, skipping installation."
+            fi
+
+            # Check if Nginx is already installed
+            if ! command -v nginx &> /dev/null
+            then
+                echo "Nginx not found, installing Nginx..."
+                sudo apt-get install nginx -y
+                echo "Nginx installation complete."
+            else
+                echo "Nginx is already installed, skipping installation."
+            fi
+
+            sudo cp ./autograder.classla.org/nginx.conf /etc/nginx/sites-available/fastapi
+
+            sudo ln -s /etc/nginx/sites-available/fastapi /etc/nginx/sites-enabled/
+            sudo nginx -t
+            sudo systemctl restart nginx
+            echo "Nginx configuration for FastAPI is complete."
+
+            sudo cp ./autograder.classla.org/fastapi.service /etc/systemd/system/fastapi.service
+
+          sudo systemctl reload nginx
+          sudo systemctl start fastapi
+          sudo systemctl enable fastapi
+
+
+          EOF
+
       - name: Pull latest changes and install requirements on server
         run: |
           ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST }} << 'EOF'
